"""initial schema

Revision ID: 20e6a6e72d76
Revises: 
Create Date: 2026-05-22 10:26:29.237588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e6a6e72d76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airbnb_id', sa.String(length=40), nullable=False),
    sa.Column('city_slug', sa.String(length=80), nullable=False),
    sa.Column('district_slug', sa.String(length=80), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(length=120), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=200), nullable=True),
    sa.Column('is_superhost', sa.Boolean(), nullable=False),
    sa.Column('size_class', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=80), nullable=True),
    sa.Column('al_status', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_slug', 'airbnb_id', name='uq_listing_city_airbnb')
    )
    op.create_table('search_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city_slug', sa.String(length=80), nullable=False),
    sa.Column('district_slugs', sa.JSON(), nullable=False),
    sa.Column('property_filter', sa.JSON(), nullable=False),
    sa.Column('classification_config', sa.JSON(), nullable=False),
    sa.Column('crawl_schedule', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crawl_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_config_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('listings_seen', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['search_config_id'], ['search_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('search_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('crawl_run')
    op.drop_table('search_config')
    op.drop_table('listing')
    # ### end Alembic commands ###
