"""listing amenity_score

Revision ID: e15724acc87a
Revises: 20e6a6e72d76
Create Date: 2026-05-28 10:49:12.867496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15724acc87a'
down_revision: Union[str, Sequence[str], None] = '20e6a6e72d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('amenity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'amenity_score')
    # ### end Alembic commands ###
